### ISSUE TITLE
Filter topics that have not been selected

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmca-blog#27]
I built my view based on the skills education and careers topic. 

The items listed also have other topics attached to them but in the search filter it only shows one option. So I couldn’t filter further to those items in the skills list that were ‘Skills’ + ‘Equality’ for example.  

Should these topics be hidden or maybe unlinked?

**Comment by saucey** [comment]
The way the filters currently work was demoed and functionality was agreed, not sure what the issue is with this functionality

**Comment by rolorogan** [comment]
When you add the blog in the CMS you have the option to choose which topics to show in the topic filter. The issue that has been reported is that a blog article can be assigned a topic which has not been selected. So we could hide these or remove the link from them
