### ISSUE TITLE
Can't filter by specific 1 day

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmca-blog#28]
Doesn’t allow you to choose a single date (ie 16 August). Asks you you include a range 

So I did 16 – 17 August and it returned 0 results. 

However this blog is published on 16th 

![Screenshot 2023-11-20 at 09 29 08](https://github.com/wmcadigital/wmca-blog/assets/7985514/2af2d62d-ad06-4b06-9d71-bcd30a86ce7b)

Should be able to search start and end on the same day.

**Comment by saucey** [comment]
I have to investigate this because the results should have returned if the blog was published on the 16th and the search started on the 16th.

**Comment by rolorogan** [comment]
Validation for the "Date To" needs to chnage from **greater than Date From** to **Greater or equal to Date From**
